<?php
/**
 * Codesicle_WishlistAjax
 *
 * @category    Codesicle
 * @package     Codesicle_WishlistAjax
 * @copyright   Copyright (c) 2019 Codesicle
 * @author      Vlad Patru <vp@codesicle.com>
 * @link        http://www.codesicle.com
 */

/**
 * @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block
 */
?>

<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
        data-mage-init='{"checkItems":{}}'
        class="action to-wishlist ajax-action"
        data-ajax-remove=''
        data-ajax-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct(), true) ?>'
        data-product-id="<?= /* @noEscape */ $block->getProduct()->getId(); ?>"
        data-action="add-to-wishlist">
        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
    </a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
